project:
  type: website
  # output-dir: docs

website:
  title: "IberFILL"
  navbar:
    left:
      - href: https://iramosgutierrez.github.io/afliber/
        text: AFLIBER website
      - href: https://doi.org/10.1111/geb.13363
        text: publication
      - href: https://afliber.shinyapps.io/afliber/
        text: Search shinyapp
  search: 
    location: navbar
    type: textbox
format:
  html:
    link-external-newwindow: true
    theme: minty
    css: styles.css
    toc: true
    linkcolor: rebeccapurple
    page-layout: full

execute:
  freeze: auto

